export {default as Navbar} from './ui/Navbar'
export {default as Hero} from './ui/Hero'
export {default as Main} from './ui/Main'
export {default as Info} from './ui/Info'
export {default as Example} from './ui/Example'
export {default as Features} from './ui/Features'
export {default as Benefits} from './ui/Benefits'